language: node_js
before_install:
  - bash echo $TRAVIS_BUILD_DIR
  - bash echo 'BEFORE INSTALL'
install:
  - bash echo $TRAVIS_BUILD_DIR
  - bash echo 'INSTALLING'
before_before_script:
  - bash echo $TRAVIS_BUILD_DIR
  - bash echo 'BEFORE BEFORE SCRIPT'
before_script:
  - bash echo $TRAVIS_BUILD_DIR
  - bash echo 'BEFORE SCRIPT'
script:
  - bash echo $TRAVIS_BUILD_DIR
  - bash echo 'SCRIPT'
